moveit_simple_controller_manager:
  controller_names:
    - dg4f_controller

  dg4f_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - j_dg_1_1
      - j_dg_1_2
      - j_dg_1_3
      - j_dg_1_4
      - j_dg_2_1
      - j_dg_2_2
      - j_dg_2_3
      - j_dg_2_4
      - j_dg_3_1
      - j_dg_3_2
      - j_dg_3_3
      - j_dg_3_4
      - j_dg_4_1
      - j_dg_4_2
      - j_dg_4_3
      - j_dg_4_4
      - j_dg_1_inner
      - j_dg_4_inner
