/**/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

# Effort Controller: 직접 effort 입력
/**/effort_controller:
  ros__parameters:
    joints:
      - j_dg_1_1
      - j_dg_1_2
      - j_dg_1_3
      - j_dg_1_4
      - j_dg_2_1
      - j_dg_2_2
      - j_dg_2_3
      - j_dg_2_4
      - j_dg_3_1
      - j_dg_3_2
      - j_dg_3_3
      - j_dg_3_4
      - j_dg_4_1
      - j_dg_4_2
      - j_dg_4_3
      - j_dg_4_4
      - j_dg_1_inner
      - j_dg_4_inner

/**/joint_state_broadcaster:
  ros__parameters:
    update_rate: 200
    joints:
      - j_dg_1_1
      - j_dg_1_2
      - j_dg_1_3
      - j_dg_1_4
      - j_dg_2_1
      - j_dg_2_2
      - j_dg_2_3
      - j_dg_2_4
      - j_dg_3_1
      - j_dg_3_2
      - j_dg_3_3
      - j_dg_3_4
      - j_dg_4_1
      - j_dg_4_2
      - j_dg_4_3
      - j_dg_4_4
      - j_dg_1_inner
      - j_dg_4_inner
